"""
Django settings for Devops_proj project.

Generated by 'django-admin startproject' using Django 2.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'm=n85xtlz$c7b-jt@og-s!s+!v&s)s(lv@1!zpdepoqq7ty+#2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['ffb93805fd1c4431b4c662b3a3a2bca6.vfs.cloud9.eu-west-1.amazonaws.com']


# Application definition

INSTALLED_APPS = [
    'expenses.apps.ExpensesConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Devops_proj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Devops_proj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
#added manually
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    '/var/www/static/',
]
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'expenses:dashboard'
LOGOUT_REDIRECT_URL = 'login'

#Added manually to send expense report to email
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com' # this is for gmail smtp server
PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'jyoti242489@gmail.com'
EMAIL_HOST_PASSWORD = 'Chatriji_00'


#AWS_ACCESS_KEY_ID = "ASIATUYJP7SUNP44TBV4"
#AWS_SECRET_ACCESS_KEY = "kpl4h2wGky8LfJQ+txtB/SVTRSYE2i4Jeq/eNWKU"
#AWS_SESSION_TOKEN = 'IQoJb3JpZ2luX2VjEE4aCXVzLWVhc3QtMSJHMEUCIQDK2JWnZWi9Lwjxi3aUX1zTvtce3fgm3tj+i6Xkda6qsQIgKnKbe9MT5PbbgC9dEsZD94T1KQVLwxdWyL4XbZfVZsMqiQQIp///////////ARADGgwyNTA3Mzg2Mzc5OTIiDNP5PbT+WBc+1OGRySrdAznO4ZPJ3xTQjJuaXOZ6wl3x+sgHITtKKrquVFPPqvZzib6rTWOll9vDhwsqgoWYO8qDwkknOrNhgHTipbG6wTDqBc1X64BlHdcHkdjSLy+tZvR6z4ezoal6oSCYqLjfJus681mwsY653bYqNHcJgwetoayOh6NktIR2EK73DzLKHKDW4KCXYuNLw9SNewNC5sjiFmLyLU02xmezGH0Nwu0FZlpPMy324S1Upef4sRKUG4bMHBpQLmBvskGu+ZSpLGb7ab2uMMAwqYgh2kGh078gjmoWcNJUiufB76aSGfo8TRZXChN5Ho8HTQO32w3KY5HkzuQSXjaEFfHj3tGU0+n33XzFoDpLaLKs+eSBnc43k3jgdHsATVCs1psQwISJw3K6cqMx+rDRL8vQhsNJ14nQpayUYLBDpgsZcqfhtEVrGvl1HP2EQZhqUALxM6P2G768Pl1y3VxlAqIVkDyn/zRraoVg6wy74P9W5xVPaDAYfxBLANYegn7Gc2p+AD1JrG9qEniofRNs6lDc5Z8/uBnoJ6r8vQkcWOH4GUa1D2aYRGdmnj/3k+gqi7EeEse0Ku5z0vRIVCy6jl8PTf/e7OgYyfa5ohMyyfQCQBXVk15vwaBp3RHIKjpVh8kXPjCS2PW+BjqmAau3A85pQGYnJBA823QMLZXKbXU6XvE1dS3hlFmGUTyqVx7qn+Fs7dPKroeBdZF2oSNmPhooZelJHcqbAT4nxeJMf13ojSiqFEq4H8Xvon9x+h3ZlkZ/ETeX6v+qiiREljlPpPf1oRT2bBeYrsI8o7Zi/GPeFWDWR44rKmbZ3LtgOJbABru586WbkB0u7P/UIACGrEVTTnjrY8pIMgLngroez9qi2+4='
AWS_S3_BUCKET_NAME = "x24104558devops"
AWS_REGION = "eu-west-1"  # e.g., us-east-1
AWS_SNS_TOPIC_ARN = "arn:aws:sns:eu-west-1:250738637992:x24104558_Devops"