version: 0.2

env:
  secrets-manager:
    SONAR_LOGIN: prod/sonar1-login
    SONAR_HOST: prod/sonar1-host
    SONAR_ORG: prod/sonar1-org
    SONAR_PROJECT: prod/sonar1-project

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt pylint
      - apt-get update
      - apt-get install -y jq unzip wget
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip sonar-scanner-cli-4.7.0.2747-linux.zip
      - export PATH=$PATH:$PWD/sonar-scanner-4.7.0.2747-linux/bin

  build:
    commands:
      - sonar-scanner \
          -Dsonar.projectKey=$SONAR_PROJECT \
          -Dsonar.organization=$SONAR_ORG \
          -Dsonar.sources=. \
          -Dsonar.host.url=$SONAR_HOST \
          -Dsonar.login=$SONAR_LOGIN
      - sleep 5
      - curl "$SONAR_HOST/api/qualitygates/project_status?projectKey=$SONAR_PROJECT" > result.json
      - if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then exit 1; fi