version: 0.2

env:
  secrets-manager:
    SONAR_SECRET: prod/sonar_x24104558  # Fetch entire secret as plaintext

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt pylint
      - apt-get update
      - apt-get install -y jq unzip wget
      # Install SonarScanner
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip sonar-scanner-cli-4.7.0.2747-linux.zip
      - export PATH=$PATH:$PWD/sonar-scanner-4.7.0.2747-linux/bin

  pre_build:
    commands:
      - python --version
      - pylint $(find $CODEBUILD_SRC_DIR -name "*.py") --fail-under=6 || true
      # Extract values from JSON secret
      - export LOGIN=$(echo "$SONAR_SECRET" | jq -r '.sonartoken')
      - export HOST=$(echo "$SONAR_SECRET" | jq -r '.HOST')
      - export Organization=$(echo "$SONAR_SECRET" | jq -r '.Organization')
      - export Project=$(echo "$SONAR_SECRET" | jq -r '.Project')
      # Verify extracted values (for debugging)
      - echo "LOGIN=$LOGIN"
      - echo "HOST=$HOST"
      - echo "Organization=$Organization"
      - echo "Project=$Project"

  build:
    commands:
      # Run Sonar Scanner
      - sonar-scanner \
          -Dsonar.projectKey=$Project \
          -Dsonar.organization=$Organization \
          -Dsonar.sources=. \
          -Dsonar.host.url=$HOST \
          -Dsonar.login=$LOGIN
      - sleep 5
      - curl "$HOST/api/qualitygates/project_status?projectKey=$Project" > result.json
      - cat result.json
      - |
        if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then
          echo "❌ Quality Gate failed"
          exit 1
        else
          echo "✅ Quality Gate passed"
        fi

artifacts:
  files:
    - '*/'