version: 0.2

env:
  secrets-manager:
    LOGIN: "arn:aws:secretsmanager:eu-west-1:250738637992:secret:prod/sonar_x24104558-BR59rO"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt pylint
      - yum update -y
      - yum install -y jq unzip wget
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip sonar-scanner-cli-4.7.0.2747-linux.zip
      - export PATH=$PATH:$PWD/sonar-scanner-4.7.0.2747-linux/bin

  build:
    commands:
      - sonar-scanner \
          -Dsonar.projectKey=$SONAR_PROJECT \
          -Dsonar.organization=$SONAR_ORG \
          -Dsonar.sources=. \
          -Dsonar.host.url=$SONAR_HOST \
          -Dsonar.login=$SONAR_LOGIN
      - sleep 5
      - curl "$SONAR_HOST/api/qualitygates/project_status?projectKey=$SONAR_PROJECT" > result.json
      - if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then exit 1; fi