version: 0.2

env:
  variables:
    LOGIN: "46457370e9d67793c91d4588f5f8c7b8961a6841"
    HOST: "https://sonarcloud.io"
    Organization: "jyoti-nci"
    Project: "Jyoti-NCI_Devops_proj"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt pylint
      - yum update -y
      - yum install -y jq unzip wget java-11-openjdk
      # Verify Java
      - java -version
      # Install SonarScanner
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip sonar-scanner-cli-4.7.0.2747-linux.zip
      - export PATH=$PATH:$PWD/sonar-scanner-4.7.0.2747-linux/bin

  pre_build:
    commands:
      - python --version
      - echo "Files in directory:"
      - find . -type f
      - pylint $(find $CODEBUILD_SRC_DIR -name "*.py") --fail-under=6 || true

  build:
    commands:
      # Debug connection first
      - echo "Testing SonarCloud connection..."
      - curl -v $HOST
      # Run Sonar Scanner with debug
      - sonar-scanner -X \
          -Dsonar.projectKey=$Project \
          -Dsonar.organization=$Organization \
          -Dsonar.sources=. \
          -Dsonar.host.url=$HOST \
          -Dsonar.login=$LOGIN
      - sleep 10
      - curl "$HOST/api/qualitygates/project_status?projectKey=$Project" > result.json
      - cat result.json
      - |
        if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then
          echo "❌ Quality Gate failed"
          exit 1
        else
          echo "✅ Quality Gate passed"
        fi

artifacts:
  files:
    - '*/'